- .travis.yml
- package.json
- sonar-project.properties
> enable Travis / Sonar #1

- .gitignore
- .vscode/launch.json
- .vscode/settings.json
- .vscode/tasks.json
- package-lock.json
- package.json
- src/extension.ts
- tsconfig.json
- tslint.json
> Open browser on a specific URL which is the default one when starting

- package.json
> Write AtlasMap in a single word #13

- README.md
> Provide badges in readme #24

- package.json
> provide configuration settings for AtlasMap URL and Port #30

- package-lock.json
- package.json
- src/extension.ts
> Remove unused chunk dependency

- .vscode/settings.json
- README.md
- package-lock.json
- package.json
- src/extension.ts
- src/test/command.test.ts
- src/test/index.ts
the input fields are prefilled with the values from the stored configuration settings and whenever the user enters something different the stored configuration values will be updated so whenever the user calls the command again it will remember what he used last time, so the user can skip over the input fields by just hitting enter twice.
> open AtlasMap command asks for url and port #19

- README.md
- package-lock.json
- package.json
- src/extension.ts
- src/requirements.ts
- src/test/requirements.test.ts
unfortunately cannot reuse code, I opened a request for that https://github.com/redhat-developer/vscode-java/issues/764 
for now I duplicated the code
> Warn user for Java requirement #27

- src/test/requirements.test.ts
please note that it is preventing to play all the other tests
> change to use describe/it instead of suite/test #28

- package.json
> provide more meta information to the package.json #50

- .travis.yml
- jars/.gitignore
> moved vsce installation to before_install #54

- Contributing.md
- avoid requiring to have npm extension install
- provide more explanation to test new version of AtlasMap
> Improve Contributing.md

- package-lock.json
- package.json
- src/extension.ts
- src/test/command.test.ts
> improve async handling with correct Promise usage #52

- package.json
- src/extension.ts
- src/test/command.test.ts
> created a stop command for AtlasMap #49

- package-lock.json
- package.json
> fixed messed up dependencies which cause the vsix to be broken #70

- .travis.yml
> Removed prepublish from travis config

- src/atlasMapWebView.ts
- src/extension.ts
- src/test/command.stop.test.ts
- src/test/command.test.utils.ts
- src/utils.ts
> closing the webview on AtlasMap Stop command #65

- src/extension.ts
> added progress popup while starting up AtlasMap #71

- .gitignore
- package.json
> added log files to gitignore

- .vscode/tasks.json
> removing unused task test #101

- src/atlasMapWebView.ts
- src/extension.ts
- src/test/outputchannel.log.test.ts
> log to an extension exclusive output channel instead of using console #97

- package.json
> Upgrade AtlasMap to 1.39.5 #105

- package-lock.json
- package.json
> Upgrade to AtlasMap 1.39.6 #107

- package-lock.json
- package.json
> Upgrade tslint to avoid js-yaml security vulnerability #108

- package.json
> upgrading to latest pre-release 1.40.0 version for new model usage

- Changelog.md
- package-lock.json
- package.json
> Prepare for next iteration 0.0.2

- Changelog.md
> Provide changelog for 0.0.2 version #126

- Jenkinsfile
> Fix naming of vsix artifact and place to push it #122

- Contributing.md
- Jenkinsfile
> Allow the whole team tp publish #122

- Jenkinsfile
> Fix syntax for list of submitter #122

- package-lock.json
- package.json
> Prepare next iteration release 0.0.3

- Changelog.md
- package.json
> Upgrade to AtlasMap 1.41.1 #132

- .travis.yml
> Move from xvfb script to xvfb service to fix Travis build #141

- package.json
- src/extension.ts
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
> Fix storagePath if there is no Folder opened in workspace (Fixes #137)

- Changelog.md
- package.json
> Update to name approved by Red Hat legal department #147

- Changelog.md
- package-lock.json
- package.json
> Prepare next iteration 0.0.4

- .gitignore
- .travis.yml
- package-lock.json
- package.json
- src/ui-test/all.ts
- src/ui-test/basic-test.ts
- src/ui-test/common/conditions.ts
- src/ui-test/common/constants.ts
- src/ui-test/common/utils.ts
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
> First UI tests for AtlasMap

- .travis.yml
> Exclude dependabot branches from non-PR jobs #165

- src/ui-test/basic-test.ts
- src/ui-test/common/utils.ts
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
> Build failures fix (Fixes #171)

- Changelog.md
- package.json
> Upgrade to AtlasMap 1.42.0 #178

- src/test/command.test.utils.ts
> Increase timeout for starting AtlasMap server #112

- Changelog.md
- package.json
> Update AtlasMap to 1.42.2 #187

- .vscodeignore
Signed-off-by: Dominik Jelinek <djelinek@redhat.com>
> Fix UI Tests startup related to new vscode-extension-tester changes

- Changelog.md
- package.json
> Upgrade to AtlasMap 1.42.5 #196

- Changelog.md
- package.json
> Upgrade AtlasMap to 1.42.10 #211

- package-lock.json
- src/ui-test/common/conditions.ts
- src/ui-test/common/utils.ts
Signed-off-by: Dominik Jelinek <djelinek@redhat.com>
> Fix UI Tests NoSuchElement errors

- package-lock.json
- package.json
- src/test/index.ts
- src/test/runTest.ts
see https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode
> FUSETOOLS2-19 - Migrate to newer VS Code test framework

- Changelog.md
- package-lock.json
- package.json
> Prepare next development iteration 0.0.5

- Changelog.md
- package.json
- src/atlasMapWebView.ts
- src/extension.ts
- src/test/command.start.test.ts
- src/ui-test/basic-test.ts
- src/ui-test/common/utils.ts
> FUSETOOLS2-62 - use asExternalUri to ease Theia/Che integration

- Changelog.md
- package.json
> FUSETOOLS2-230 - upgrade AtlasMap to 1.43.4

- src/atlasMapWebView.ts
https://sonarcloud.io/project/issues?id=vscode-atlasmap&issues=AXAU0mxdxAwNLZ01lo78&open=AXAU0mxdxAwNLZ01lo78
> Remove unused import

- Changelog.md
- package-lock.json
- package.json
> Prepare next iteration 0.0.6

- package-lock.json
- package.json
- upgrades vscode engine to 1.44.0
- removes the version specification for ui-test
> updated vscode engine to 1.44.0 and removed version specification for ui-test

- package.json
> bump @types/vscode to 1.44.0

- src/AtlasMapPanel.ts
> Make the viewport fluid.

- package-lock.json
- package.json
Signed-off-by: Dominik Jelinek <djelinek@redhat.com>
> Update vscode-extension-tester to 3.0.1

- Changelog.md
- package.json
> FUSETOOLS2-503 - upgrade AtlasMap from 2.0.4 to 2.0.5

- Changelog.md
- package-lock.json
- package.json
> Prepare next development iteration 0.0.7

- src/test/command.start.test.ts
- src/test/command.test.utils.ts
> FUSETOOLS2-611 - fixing flaky tests

- Changelog.md
- package.json
> FUSETOOLS2-667 - upgrade AtlasMap from 2.0.5 to 2.0.7

- Changelog.md
- package.json
> FUSETOOLS2-770 - bump AtlasMap version to 2.1.0

- README.md
> FUSETOOLS2-825 - Update badge for Travis moving from .org to .com

- src/extension.ts
> fixed some code smell reported by sonar

- src/AtlasMapPanel.ts
- src/extension.ts
> a couple more fixes for code smells

- .circleci/config.yml
> restructuring cci config

- .circleci/config.yml
> FUSETOOLS2-852/853 - removing obsolete entry for environment config

- .circleci/config.yml
> FUSETOOLS2-852/853 - allow builds for dependabot branches / PRs

- README.md
> fix: Provide Atlasmap getting started guide in README.md

- Changelog.md
- package.json
> FUSETOOLS2-936 - Upgrade AtlasMap from 2.1.0 to 2.1.1

- Changelog.md
- package.json
> FUSETOOLS2-940 - upgrade to AtlasMap 2.1.2

- Changelog.md
- package.json
> upgrade to AtlasMap 2.1.3

- README.md
Fixed due to updates from AtlasMap PR [2534](https://github.com/atlasmap/atlasmap/pull/2534)
> #513: Update README.md once AtlasMap User's Guid is updated

- Changelog.md
- package-lock.json
- package.json
> FUSETOOLS2-995 - upgrade AtlasMap to 2.1.5

- Changelog.md
- package.json
- src/extension.ts
message in log that is used to detect that the server has started has
changed
> FUSETOOLS2-1096 - upgrade to VS Code AtlasMap 2.2.0

- Changelog.md
- package.json
> FUSETOOLS2-1129 - Upgrade AtlasMap to 2.2.2

- src/ui-test/basic-test.ts
Signed-off-by: Dominik Jelinek <djelinek@eredhat.com>
> Remove UI test workaround to make tests passing

- Changelog.md
- package.json
> upgrade to AtlasMap 2.2.3

- .vscode/launch.json
- Changelog.md
- README.md
- USAGE_DATA.md
- package-lock.json
- package.json
- src/extension.ts
- src/test/command.start.test.ts
- src/test/command.stop.test.ts
allows to provide this kind of reports https://app.woopra.com/project/test.vscode/analyze/report/trends/hdsehizqub or https://app.woopra.com/project/test.vscode/analyze/report/trends/dxsfyikk4o
> FUSETOOLS2-1267 - Provide opt-in telemetrics for usage

- .circleci/config.yml
- Jenkinsfile
relates to https://gitlab.cee.redhat.com/codeready-studio/cci-config/-/merge_requests/460
needs to update default branch name in GitHub web UI before merging
> FUSETOOLS2-1302 - migrate master to main branch

- Changelog.md
- package-lock.json
- package.json
planned an important modification by using AtlasMap inside an editor,
that's why increasing minor version
> prepare for next development iteration 0.1.0

- README.md
> FUSETOOLS2-1376 - provide information on version matching with runtime

- Changelog.md
- README.md
- package-lock.json
- package.json
- src/extension.ts
- src/test/commands/atlasmap.file.create.test.ts
> FUSETOOLS2-1372 - adding a command to create and open an adm file

- USAGE_DATA.md
> Update usage data, include new command

- Changelog.md
- README.md
- package-lock.json
- package.json
> Prepare for next development iteration 0.1.1

- Changelog.md
- package-lock.json
- package.json
I do not expct that this will be ever used but better to let things clean just in case
> Next maintenance development iteration 0.0.11

- Changelog.md
- package.json
> FUSETOOLS2-1406 - upgrade to AtlasMap 2.4.0-M2

- README.md
> Update version matching in readme

- Changelog.md
- package.json
> FUSETOOLS2-1408 - upgrade to AtlasMap 2.4.0-M3

- README.md
of course I remembered of it, just when i clicked on merge pull request for the previous PR that was doing the upgrade
> FUSETOOLS2-1408 - update readme about upgrade to AtlasMap 2.4.0-M3

- Changelog.md
- src/extension.ts
> Fix opening of AtlasMap editor on windows

- Changelog.md
- README.md
- package-lock.json
- package.json
> Next development iteration 0.1.3

- src/ui-test/editor.ts
> FUSSETOOLS2-1592 - increase timeout for save as test to have test

- .github/workflows/os-matrix.yml
> Store logs and screenshots of UI test failures for github CI workflow

- .github/dependabot.yml
- Jenkinsfile
- package.json
Left Lars as a contributtor this time as he still contributed to the codebase and it made sense
But if it was a mistake feel free to comment/edit :)
> [FUSETOOLS2-1644] Updated developers info. 

- package.json
- src/ui-test/editor.ts
Signed-off-by: Dominik Jelinek <djelinek@redhat.com>
> FUSETOOLS2-1592: Fix UI tests infinite waiting loop

- Changelog.md
- README.md
- package-lock.json
- package.json
Tested manually:
- basic workflows (note that there is a regression not introduced by this PR on a basic use case https://issues.redhat.com/browse/FUSETOOLS2-1691 )
- creating very basic adm with 0.1.x and opening it in 0.2.x. it was acknowledged that it is ok to take the risk not to do extensive testing on this use case
> Use AtlasMap 2.4.0

- package-lock.json
- package.json
- src/test/runTest.ts
Related issue: https://issues.redhat.com/browse/FUSETOOLS2-1733
> FUSETOOLS2-1733: Migrate to @vscode/electron

- Changelog.md
- README.md
- package.json
> FUSETOOLS2-1707 - upgrade to AtlasMap 2.5.0

- Changelog.md
- README.md
- package-lock.json
- package.json
> Preparing version 0.2.1

- .github/workflows/os-matrix.yml
- src/test/commands/atlasmap.file.create.test.ts
> Reactivate Windows on CI matrix
