jboss-fuse/vscode-atlasmap

.travis.yml
.vscodeignore
Contributing.md

https://github.com/jboss-fuse/vscode-atlasmap/pull/22 to be merged first
I've done it manually and it was successfully deployed:
```
C:\git\vscode-atlasmap>vsce publish -p <theVSCodeTokenThatIConfiguredOnTravisCI>
Executing prepublish script 'npm run vscode:prepublish'...
> atlasmap-viewer@0.0.1 vscode:prepublish C:\git\vscode-atlasmap
> tsc -p ./
Publishing jboss-fuse.atlasmap-viewer@0.0.1...
Successfully published jboss-fuse.atlasmap-viewer@0.0.1!
Your extension will live at https://marketplace.visualstudio.com/items?itemName=jboss-fuse.atlasmap-viewer (might take a few seconds for it to show up).
```
I've deleted the extension after to ensure that the first publish will work :-)

publish vsix

---

package.json

removed the obsolete atlasmap command from activation events #56

---

src/atlasMapWebView.ts
src/test/command.start.test.ts

it allows to take the whole space in UI

Override padding style from VS Code to match AtlasMap one #69

---

package-lock.json
package.json
src/extension.ts
src/test/command.combined.test.ts
src/test/command.start.test.ts
src/test/command.stop.test.ts

instead of opn external library
I discovered that VS Code is providing a command which is handling opening an URL in default system browser. It might be more performant than the opn library.

Use VS Code command to open AtlasMap UI #86

---

package-lock.json
package.json
scripts/preinstall.js
src/extension.ts
src/test/command.start.test.ts
src/test/command.test.utils.ts

This PR will make the Open AtlasMap an action on a ADM file in the explorer view. When executed it will pass the path of the adm file as `-Datlasmap.adm.path=<path>` to the startup of the atlasmap-standalone. 
For now I am not able to test if the file gets imported in AtlasMap correctly because https://github.com/atlasmap/atlasmap/issues/755 is still not implemented.
@pleacu @igarashitm FYI
fixes #7

handover ADM file path to AtlasMap startup #7

---

Contributing.md
README.md

- remove information that we can use an external AtlasMap server as it
is no more the case
- add information to debug the VS Code WebView

Update contributing guide

---

src/extension.ts
src/test/outputchannel.log.test.ts

if another tests was logging, the test was failing and irrelevant

Make test independent from others #112

---

src/extension.ts

so now we can call the log with an Error object.
it avoids this error: "stack trace: TypeError [ERR_INVALID_ARG_TYPE]:
The first argument must be one of type string, Buffer, ArrayBuffer,
Array, or Array-like Object. Received type object"

Support log with any kind of parameter #112

---

Changelog.md
src/extension.ts
src/test/ActivateDeactivateExtension.test.ts

Notably, it deactivates when VS Code shutdowns. it avoids to have a
resource leaks of AtlasMap instance on Mac.

FUSETOOLS2-44 : stop AtlasMap instance when VS Code extension deactivate

---

src/atlasMapWebView.ts

it avoids to call a refresh when switching between tabs and getting back
to the webview. Consequently, it avoids some latency and most important
it workarounds a bug inside AtlasMap
https://github.com/atlasmap/atlasmap/issues/1455
the drawback is that the memory is still kept when the tab is hidden.
Given that for now we can open a single tab at a time, this is not a
major problem.

FUSETOOLS2-45 - retain context of webview

---

Jenkinsfile

this extension has a different pattern for naming for historical
reasons. It requires then to adjust the packaging steps.
For the sake of consistency with other extensions, keeping the
vscode-atlasmap-xx naming for the output
it si fixing current master build failure https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/VS%20Code/job/vscode-atlasmap-release/101/console
```
+ mv vscode-atlasmap-0.0.5.tgz vscode-atlasmap-0.0.5-101.tgz
mv: cannot stat ‘vscode-atlasmap-0.0.5.tgz’: No such file or directory
```

FUSETOOLS2-80 - fix Jenkins packaging

---

package.json
src/AtlasMapPanel.ts
src/extension.ts
src/test/command.start.test.ts

It looks like iframes inside a webview are buggy/limited. This loads
Atlasmap directly inside the webview skipping the iframe step.
Fixes #371

Load Atlasmap directly in the webview

---

package-lock.json
package.json
src/test/command.start.test.ts

now that the content of index.html is retrieve dynamically, we need to
provide a conditional wait in tests to ensure that it had time to load
the content of AtlasMap UI

FUSETOOLS2-469 - have deterministic test checking for AtlasMap opened

---

src/test/command.start.test.ts

use await and async to have conditional wait respected …
the waitUntil wasn't respected before because it wasn't an async method
and no await was used. Consequently, the test was passing only when
there is no need of it. There was only a trace in log of a timeout
unresolved promise but it wasn't failing the test

Fusetools2 672 fix master on jenkins

---

.travis.yml
Jenkinsfile

it allows to ensure that the package-lock.json is respected

FUSETOOLS2-702 - use npm ci instead of npm install

---

package-lock.json

to fix master, to have it compatible with VS Code 1.50.0

FUSETOOLS2-783 - upgrade vscode-extension-tester-locators to 1.50.0

---

.travis.yml

it will allow to stay aligned with jenkins

FUSETOOLS2-748 - use lts version of node on Travis

---

Contributing.md

it avoids to update manually package-lock.json or to call npm install
that can introduce a lot of unrelated change

use command to update version

---

Changelog.md
src/AtlasMapPanel.ts

on first click after loading AtlasMap Ui in Theia, the UI is reloading.
It also reloads when the view is gaining or losing focus.
It is caused because Theia is triggering the event when gaining/losing
focus although VS Code sends it only when hiding/revealing.
A test would need to be added on Theia/Che side, do not see well how we
can test it efficiently on VS Code side.
Note: maybe we can completely remove the reload, or use a lighter
refresh mode. I think this would need to be investigated is a separated
PR as it can have a lot of impacts.
To test this PR:
* clone theia (currently with this [branch](https://github.com/apupier/theia/tree/5007-avoidRedirectLoop) until this [PR](https://github.com/eclipse-theia/theia/pull/10063) is merged)
* call `yarn`
* generate vsix from the branch of …

FUSETOOLS2-1280 - Avoid reloading issue in Theia

---

.circleci/config.yml
Changelog.md
src/requirements.ts

circleci/* are deprecated and to be replaced with cimg/*

FUSETOOLS2-1292 - migrate Docker image on Circle CI

---

.circleci/config.yml

- switch back to node 14. (not compatible with Node 16)
- avoid sudo use for global dependencies installation

1359 fix main

---

Contributing.md

Document how to test another version of AtlasMap standalone without

---

src/ui-test/editor.ts

this is a shame that it requires [35 seconds](https://app.circleci.com/pipelines/github/jboss-fuse/vscode-atlasmap/682/workflows/7e9eae24-05bb-460b-ac48-c72ba731c102/jobs/970?invite=true#step-109-46) to open 2 times AtlasMap on CI :-(
(means that for users with slow machine this is hardly sustainable)

FUSETOOLS2-1388 - increase timeout to avoid failures on CircleCI

---

.github/workflows/os-matrix.yml

Linux is currently handled by Circle CI
created on GitHub Actions because it is infinitely easier than on Circle CI with a mix of node and Java requirement

FUSETOOLS2-1409 - Provide CI job for Windows and Mac

---

package.json

it allows to better reconcile the same setting shared between several
extensions

FUSETOOLS2-1490 - provide tags telemetry on telemetry setting

---

.github/workflows/os-matrix.yml

see https://github.com/atlasmap/atlasmap/issues/3969 and
https://bugs.openjdk.java.net/browse/JDK-8285445

Until Java 11.0.16 is release, deactivating windows tests

---

package-lock.json
package.json
src/extension.ts
src/test/commands/atlasmap.file.create.test.ts

switch back to valid-filename 3.1.0. Seems 4.0.0 requires "module" and
does not support the "CommonJS" which seems to be require din this
project so far. Created https://issues.redhat.com/browse/FUSETOOLS2-1693 to handle the upgrade later.
In case, we use the 4.0.0 with the provided syntax, ther eis this error:
Activating extension 'redhat.atlasmap-viewer' failed: require() of ES
Module /home/apupier/git/vscode-atlasmap/node_modules/valid-filename/index.js
from /home/apupier/git/vscode-atlasmap/out/extension.js not supported.
Instead change the require of index.js in
/home/apupier/git/vscode-atlasmap/out/extension.js to a dynamic import()
which is available in all CommonJS modules..
it would be nice to have a UI test, I started investigation but will need QE team to look at it to make it …

FUSETOOLS2-1691 - fix create new file

---

Contributing.md

Updated Jenkins URL to correct URL (last one is broken)
Updated JBoss Downloads to put the url with the snapshots, which is the place where you can get the vsix

Updating wrong URLs

---

Changelog.md
src/commands/file/create.ts
src/extension.ts
src/test/commands/atlasmap.file.create.test.ts

Related issue: https://issues.redhat.com/browse/FUSETOOLS2-1737
Provides a choice to select a directory inside the workspace for the adm file.

FUSETOOLS2-1737 - Allow choice of placement of .adm file

---

Changelog.md
src/commands/file/create.ts
src/test/commands/atlasmap.file.create.test.ts

Related ticket: https://issues.redhat.com/browse/FUSETOOLS2-1811
This fixes the issue where the validator was only validating at workspace root. Added some new tests that assert that the behaviour is as expected.
I'll be releasing this tomorrow after merging in 0.2.2

Validate filename bug

---

package.json

awaiting a release with a fix for https://github.com/redhat-developer/vscode-extension-tester/issues/545 , it allows to have main branch green again. the problem is not impacting the vs code extension in itself.

Test with VS Code 1.73 awaiting for 1.74 support of extension-tester

---

.github/workflows/main.yaml
Jenkinsfile

On Jenkins CI host, the ipV6 is now deactivated.
otherwise somewhere between the host and the npmjs website ipV6, a layer is not handling it correctly.

FUSETOOLS2-2176 - use Node 18 for build
